### ISSUE TITLE
Images hosted using Cloudflare images and CDN with broken links

### ISSUE THREAD

**Issue by henningbra** [ccjmne/puppeteer-html2pdf#10]
Thanks for a quick startup using the docker image. Currently testing and many sites comes out great with this tool.

We are building tools for an human elephant conflict mitigation foundation. 

Our [backend](https://hec.naturewildlifeassoc.org/) are using Cloudflare Images/CDN and they may be delivered as JPG, AVIF or WEBP, not sure what the reason is but all image links are broken as shown in the partial snippet from the PDF below generated from the frontpage:

![image](https://github.com/ccjmne/puppeteer-html2pdf/assets/5746249/43cc6811-3000-4b43-9754-613f41dee7c3)

**Comment by henningbra** [comment]
Have tested with the same results:

- 2.1.0
- 2.0.0
- 1.5.2

**Comment by henningbra** [comment]
Switched to [https://github.com/gotenberg/gotenberg](https://github.com/gotenberg/gotenberg) and it works with all files including css, js and images.

**Comment by henningbra** [comment]
Found the issue. When HTML dumped I had relative paths to assets and therefore broken.

I'm sorry. Should I delete this issue?

**Comment by ccjmne** [comment]
Ah, thanks for getting to the bottom of this!
Good luck with your project :)
